import { TestBed } from '@angular/core/testing';
import { InsuranceTrackerService, type InsurancePolicy } from './insurance-tracker.service';

describe('InsuranceTrackerService', () => {
  let service: InsuranceTrackerService;

  /** Build a policy fixture; `id` is generated by addPolicy in tests that hit the real path. */
  const policyInput = (over: Partial<Omit<InsurancePolicy, 'id'>> = {}): Omit<InsurancePolicy, 'id'> => ({
    propertyId: 'prop-1',
    insurer: 'Fidelidade',
    policyNumber: 'P-0001',
    type: 'multirriscos',
    startDate: '2026-01-01',
    endDate: '2027-01-01',
    premium: 240,
    ...over,
  });

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(InsuranceTrackerService);
  });

  it('starts with an empty policy list', () => {
    expect(service.policies()).toEqual([]);
    expect(service.activePolicies()).toEqual([]);
    expect(service.expiringSoon()).toEqual([]);
    expect(service.expired()).toEqual([]);
    expect(service.byProperty().size).toBe(0);
  });

  it('addPolicy assigns a unique id and appends to the list', () => {
    const a = service.addPolicy(policyInput());
    const b = service.addPolicy(policyInput({ policyNumber: 'P-0002' }));
    expect(a.id).toBeTruthy();
    expect(b.id).toBeTruthy();
    expect(a.id).not.toBe(b.id);
    expect(service.policies().length).toBe(2);
    expect(service.policies()[0]).toEqual(a);
  });

  it('removePolicy strips by id and is a no-op for unknown ids', () => {
    const a = service.addPolicy(policyInput());
    const b = service.addPolicy(policyInput({ policyNumber: 'P-0002' }));
    service.removePolicy(a.id);
    expect(service.policies()).toEqual([b]);
    service.removePolicy('does-not-exist');
    expect(service.policies()).toEqual([b]);
  });

  it('renewPolicy updates endDate of a matched policy only', () => {
    const a = service.addPolicy(policyInput({ endDate: '2026-06-01' }));
    const b = service.addPolicy(policyInput({ policyNumber: 'P-0002', endDate: '2026-08-01' }));
    service.renewPolicy(a.id, '2027-06-01');
    const found = service.policies().find(p => p.id === a.id)!;
    const other = service.policies().find(p => p.id === b.id)!;
    expect(found.endDate).toBe('2027-06-01');
    expect(other.endDate).toBe('2026-08-01');
  });

  it('renewPolicy on unknown id is a no-op', () => {
    service.addPolicy(policyInput({ endDate: '2026-06-01' }));
    const before = service.policies();
    service.renewPolicy('nope', '2099-01-01');
    expect(service.policies()).toEqual(before);
  });

  it('activePolicies excludes lapsed policies based on today()', () => {
    service.today.set('2026-06-01');
    service.addPolicy(policyInput({ endDate: '2026-12-31' })); // active
    service.addPolicy(policyInput({ policyNumber: 'P-0002', endDate: '2026-05-31' })); // expired
    expect(service.activePolicies().length).toBe(1);
    expect(service.activePolicies()[0].endDate).toBe('2026-12-31');
  });

  it('expiringSoon flags policies ending in 0..30 days inclusive', () => {
    service.today.set('2026-06-01');
    service.addPolicy(policyInput({ endDate: '2026-06-01' })); // 0 days → flagged
    service.addPolicy(policyInput({ policyNumber: 'P-0002', endDate: '2026-07-01' })); // 30 days → flagged
    service.addPolicy(policyInput({ policyNumber: 'P-0003', endDate: '2026-07-02' })); // 31 days → not flagged
    service.addPolicy(policyInput({ policyNumber: 'P-0004', endDate: '2026-05-31' })); // expired → not flagged
    const nums = service.expiringSoon().map(p => p.policyNumber).sort();
    expect(nums).toEqual(['P-0001', 'P-0002']);
  });

  it('expired returns only policies past their endDate', () => {
    service.today.set('2026-06-01');
    service.addPolicy(policyInput({ endDate: '2026-05-30' }));
    service.addPolicy(policyInput({ policyNumber: 'P-0002', endDate: '2026-06-01' })); // today → still active
    service.addPolicy(policyInput({ policyNumber: 'P-0003', endDate: '2026-12-31' }));
    expect(service.expired().length).toBe(1);
    expect(service.expired()[0].policyNumber).toBe('P-0001');
  });

  it('byProperty groups policies under their propertyId', () => {
    service.addPolicy(policyInput({ propertyId: 'prop-1' }));
    service.addPolicy(policyInput({ propertyId: 'prop-1', policyNumber: 'P-0002', type: 'rc' }));
    service.addPolicy(policyInput({ propertyId: 'prop-2', policyNumber: 'P-0003' }));
    const grouped = service.byProperty();
    expect(grouped.size).toBe(2);
    expect(grouped.get('prop-1')!.length).toBe(2);
    expect(grouped.get('prop-2')!.length).toBe(1);
  });

  it('reset clears the policy list', () => {
    service.addPolicy(policyInput());
    service.addPolicy(policyInput({ policyNumber: 'P-0002' }));
    expect(service.policies().length).toBe(2);
    service.reset();
    expect(service.policies()).toEqual([]);
    expect(service.byProperty().size).toBe(0);
  });

  it('treats invalid endDate as 0 days remaining (flagged as expiringSoon, not expired)', () => {
    // daysBetween returns 0 on NaN parse → policy is treated as "expiring today" (>= 0 && <= 30).
    service.today.set('2026-06-01');
    service.addPolicy(policyInput({ endDate: 'not-a-date' }));
    expect(service.expired().length).toBe(0);
    expect(service.expiringSoon().length).toBe(1);
  });
});
