name: Release & Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@israelclucena'
      - name: Install dependencies
        run: npm ci
      - name: Build core lib
        run: npx nx build core
      - name: Run tests
        run: npx nx test core --watchAll=false --passWithNoTests
      - name: Publish to GitHub Packages
        run: |
          cd dist/libs/core
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
